### ISSUE TITLE
unable to run game

### ISSUE THREAD

**Issue by andy5995** [LoveDaisy/tetris_game#3]
I'm using Manjaro 21.2.1. I get errors as soon as I try running the game:

```
[andy@prometheus tetris_game]$ python3 tetris_game.py 
=== 0:00:00.022621
Traceback (most recent call last):
  File "/home/andy/src/tetris_game/tetris_game.py", line 178, in paintEvent
    drawSquare(painter, x * self.gridSize + dx, y * self.gridSize + dy, val, self.gridSize)
  File "/home/andy/src/tetris_game/tetris_game.py", line 148, in drawSquare
    painter.fillRect(x + 1, y + 1, s - 2, s - 2, color)
TypeError: arguments did not match any overloaded call:
  fillRect(self, QRectF, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, QRect, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, QRectF, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, QRect, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, QRect, Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, QRectF, Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, QRect, Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, QGradient.Preset): argument 1 has unexpected type 'float'
  fillRect(self, QRect, QGradient.Preset): argument 1 has unexpected type 'float'
  fillRect(self, QRectF, QGradient.Preset): argument 1 has unexpected type 'float'
Aborted (core dumped)
```

**Comment by LoveDaisy** [comment]
sorry about that. It is a python 2 project, and I didn't pay much attention to make it compatible to python 3. I guess that's why you get this error message. You may try python 2. Or if you are familiar with python 3, please feel free to make a PR :)

**Comment by andy5995** [comment]
Thanks for letting me know. The README mentions python3 and that's one of the tags used in the project description.

I have very little experience with python2 or 3, but I'll wish you luck :)

**Comment by LoveDaisy** [comment]
I only test it on python 3.2, which is a quite early version. I guess there are still some incompatibilities on later version.
